### ISSUE TITLE
Anchors in attr_list are reported as invalid urls

### ISSUE THREAD

**Issue by diegorondini** [manuzhang/mkdocs-htmlproofer-plugin#32]
**Describe the bug**
When enabling the `attr_list` extension:
https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
https://python-markdown.github.io/extensions/attr_list/
the following anchor link is valid:
```
![My image](image.png){ #my-image-anchor }

Blah blah [my image reference](#my-image-anchor)
```
but mkdocs-htmlproofer-plugin will report it as invalid url:
```
invalid url - #my-image-anchor [404] [mypage.md]
```

Contents of `mkdocs.yml`:

```yaml
markdown_extensions:
  - attr_list

plugins:
  - search
  - htmlproofer:
      validate_external_urls: False
```
