### ISSUE TITLE
Question: how to handle/ignore `-1` errors

### ISSUE THREAD

**Issue by emmercm** [manuzhang/mkdocs-htmlproofer-plugin#63]
**Describe the bug**

I'm getting a `-1` error that I'm assuming means a timeout:

```text
 WARNING  -  htmlproofer: invalid url - http://www.logiqx.com/DatFAQs/CMPro.php [-1] [dats.md]
```

I can't seem to ignore this in my `mkdocs.yml`:

```yaml
plugins:
  - htmlproofer:
      raise_error_excludes:
        '-1': [ 'http://www.logiqx.com' ]
```

**To Reproduce**

Add a link to http://www.logiqx.com/DatFAQs/CMPro.php or some other website that's timing out and then run `mkdocs`.

**Environment (please complete the following information):**

- OS (e.g. Windows 10/Ubuntu 20.04/macOS): macOS Ventura 13.2.1
- Python version (`python --version`): v3.10.8
- Package versions (`pip list`): v0.12.0

Contents of `mkdocs.yml`:

```yaml
plugins:
  - htmlproofer:
      raise_error_excludes:
        '-1': [ 'http://www.logiqx.com' ]
```
