### ISSUE TITLE
Retries & 429 Too Many Requests

### ISSUE THREAD

**Issue by louwers** [manuzhang/mkdocs-htmlproofer-plugin#86]
When checking a lot of URLs of the same origin, it is very easy be rate-limited and get a [429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) response.

It would be neat if some retry logic could be added. The simplest implementation would simply look for a `Retry After` header. https://stackoverflow.com/a/63684455/1929678

**Comment by manuzhang** [comment]
@johnthagen WDYT?

**Comment by johnthagen** [comment]
Hmm, I don't see it as a bad idea but it could add a lot of complexity to the project?

@louwers Does this work as a workaround?

```yaml
  - htmlproofer:
      raise_error: True
      raise_error_excludes:
        429: ['https://www.mkdocs.org/']
```

It feels a bit more flexible and if you know you are going to hit a certain URL a lot, you can simply count `429`s as "passes"?
